version: 2.1
orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - name: Install dependencies
      - run:
          npm i
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: Run npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run lint
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  on_commit:
    jobs:
      - build_and_test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"       
          filters:
            branches:
              only:
                - master
                - docs-node-js-language-guide
    jobs:
      - build_and_test
